# Change these first
owner: globalregulation # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Regnet Landing Page
    url: https://regnet.pro
  - name: Regnet Application Page
    url: https://app.regnet.pro
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.regnet.pro
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Regnet Upptime
  introTitle: "Uptime monitoring for regnet.pro"
  introMessage: This is a status page for regnet.pro
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
